### PR TITLE
Add 'Can shorebird see my code' to FAQ

### PR DESCRIPTION
**Pull request by bryanoltman**
We've received a number of questions from (potential) users re: the level of access we have to their code and what we store. This adds an FAQ entry to address that.

### CODE REVIEW

**Review by felangel — COMMENTED** [review]
This looks the same as https://docs.shorebird.dev/faq/#does-shorebird-store-my-source-code. I think we might want to consolidate the FAQs. The docs seem like a good place to move everything since they are indexed and search-able.

**Comment by eseidel** [comment]
Agreed, but this one comes up frequently enough we should have something on our front page I think.   I'm writing up a similar patch which I'll send you shortly.

**Comment by bryanoltman** [comment]
> this one comes up frequently enough we should have something on our front page I think

This is on our front page?

**Comment by bryanoltman** [comment]
To be clear, I don't feel strongly that this is exactly what we need to say and am fine with a different PR landing, just want to make sure we're talking about the same thing.

**Pull request closed without merging**
